name: GitHub Pages

on:
  push:
    branches:
      - master # Set a branch name to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create output directory
        run: |
          mkdir output
      - name: Build HTML file
        uses: docker://pandoc/latex:2.14.1
        with:
          args: >-
            --standalone lkmpg.tex
            --output=output/index.html
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: gh-pages
